-
  name: "Sweet dreams!"
  desc: |
    Niki and Jazmin’s new book has two stories.

    The title of the first story is: Snowy Adventure. In this story you can read about a pleasant winter day, you can find out how Niki and Jazmin fooled Daddy, how the family went for sledging, how did Niki and Jazmin climbed up the steep hill and a lot more.

    The second story is: Good night! From this story you can learn how Niki and Jazmin are preparing for the bed time. How many good night kisses and how many hugs it takes to get the girls to fall asleep? “Mommy, one more goodnight kiss, please … can you give me one more hug … Mommy, I’m thirsty … Mommy, I can not find Little Cow... Mommy, I can not find Small Giraffe … Mommy, I have to pee … please cover me once more!”  Are these familiar to you too?
  product_type: book
  icon: "/images/sweetdreams_book.jpg"
-
  name: "Come, play with us!"
  desc: |
    Come, play with us! is a book for iPad with five stories about Niki & Jazmin. You can meet the girls while playing on the playground, being in the library, creating a new toy swing for their favourite animals. You can hear the story about how Mommy and Jazmin visited the doctor and you can see how did Niki end up in the bathtub fully- clothed.
      * list 1
      * list 2

    This book has 68 pages.
  store_link: "https://itunes.apple.com/fi/book/come-play-with-us!/id579269946?mt=11"
  product_type: book
  icon: "/images/comeplaywithus_book.jpg"
  release_date: 2012-11-15
-
  name: "Niki and Jazmin's Christmas"
  desc: |
    Every child is excited about what they will find under the Christmas tree. Until the arrival of  Christmas Eve there are many interesting things we can do together. Come and spend the Advent season with Niki and Jazmin and see how they are preparing for Christmas and see what they will find under their Christmas tree.
    This book has 21 pages.
  store_link: "https://itunes.apple.com/fi/book/niki-and-jazmins-christmas/id580481514?mt=11"
  product_type: book
  icon: "/images/xmas_book.jpg"
  release_date: 2012-11-20
-
  name: Spot The Difference
  desc: |
    Spot the difference in 18 wonderful pictures from the books of Niki and Jazmin!

    There are 2 levels: easy and difficult. In easy level you have to find 3 out of 5 differences to get a yellow star. In difficult level you have to find all 5 differences between two pictures to get a red star. In the menu you can follow how many stars you have collected.

    Are you able to find all the differences? Can you collect all the stars? 
  icon: "/images/spotthedifference_icon.png"
  wide_banner: "/images/spotTheDifference.jpg"
  product_type: app
-
  name: Sticker Album
  desc: |
    There are three different scenes in this application which you can decorate based on your own taste. 

    * Design and decorate the wallpaper of Niki and Jazmin’s room 
    * Make the doctor’s waiting room cosier and play with the toys 
    * Plant your own flowers, bushes and trees in the garden, so that every kind of insects and little animals could find their home.

    [Watch the video on YouTube](http://youtu.be/meor6G9_yg0)
  icon: "/images/stickeralbum_icon.png"
  product_type: app
  store_link: "https://itunes.apple.com/fi/app/stickeralbum/id593319772?mt=8"
  release_date: 18-01-2013
-
  name: The toy swing
  desc: |
    The toy swing is an interactive book for iPad. You can follow the story about Niki & Jazmin making a new toy swing with Mommy for their stuffed animals. You can also play with some toys, make interaction with many figures. While listening to the story you can also play a treasure hunt - find all hidden starts on each page!
    There is also a memory game in the end of the story.

    [Watch the video on YouTube](http://youtu.be/uf__qABMOZ0)
  icon: "/images/toyswing_icon.png"
  product_type: app
  store_link: "https://itunes.apple.com/fi/app/toyswing/id582249285?mt=8"
  release_date: 12-02-2013
