-
  name: "Sweet dreams!"
  desc: |
    Niki and Jazmin’s new book has two stories.

    The title of the first story is: Snowy Adventure. In this story you can read about a pleasant winter day, you can find out how Niki and Jazmin fooled Daddy, how the family went for sledging, how did Niki and Jazmin climbed up the steep hill and a lot more.

    The second story is: Good night! From this story you can learn how Niki and Jazmin are preparing for the bed time. How many good night kisses and how many hugs it takes to get the girls to fall asleep? “Mommy, one more goodnight kiss, please … can you give me one more hug … Mommy, I’m thirsty … Mommy, I can not find Little Cow... Mommy, I can not find Small Giraffe … Mommy, I have to pee … please cover me once more!”  Are these familiar to you too?
  product_type: book
  icon: "/images/sweetdreams_book.jpg"
-
  name: "Come, play with us!"
  desc: |
    Come, play with us! is a book for iPad with five stories about Niki & Jazmin. You can meet the girls while playing on the playground, being in the library, creating a new toy swing for their favourite animals. You can hear the story about how Mommy and Jazmin visited the doctor and you can see how did Niki end up in the bathtub fully- clothed.
      * list 1
      * list 2

    This book has 68 pages.
  store_link: "https://itunes.apple.com/fi/book/come-play-with-us!/id579269946?mt=11"
  product_type: book
  icon: "/images/comeplaywithus_book.jpg"
  release_date: 2012-11-15
-
  name: "Niki and Jazmin's Christmas"
  desc: |
    Every child is excited about what they will find under the Christmas tree. Until the arrival of  Christmas Eve there are many interesting things we can do together. Come and spend the Advent season with Niki and Jazmin and see how they are preparing for Christmas and see what they will find under their Christmas tree.
    This book has 21 pages.
  store_link: "https://itunes.apple.com/fi/book/niki-and-jazmins-christmas/id580481514?mt=11"
  product_type: book
  icon: "/images/xmas_book.jpg"
  release_date: 2012-11-20

